## Issue description:


### Steps to reproduce:


### Expected behavior:


### Actual behavior:


### Links to logs:

A link to logs posted on http://pastebin.com/ (or any other publicly reachable service).

### Are you able to reproduce the issue with `selinon-cli execute`?


### Selinon & Celery version:

Running `selinon-cli version` gave me:


- [ ] I have tried the latest master but the issue still pesists:
  `pip3 install --force-reinstall git+https://github.com/selinon/selinon@master`

### Links to YAML config files:


### Links to task implementations:


